let global = {}

global.TERMINATED = false;
global.MINIBLOCKCHAIN_LIGHT_CONFIGURATION_SAVED = true;
global.MINIBLOCKCHAIN_LIGHT_SAVED = true;
global.MINIBLOCKCHAIN_ADVANCED_SAVED = true;
global.MINIBLOCKCHAIN_SAVED = true;
global.INTERFACE_BLOCKCHAIN_SAVED = true;
global.INTERFACE_BLOCKCHAIN_LOADING = false;
global.SEMAPHORE_PROCESS_DONE = true;

export default global